using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;
using static Unity.Mathematics.math;

namespace Zori.Entities.Physics2D.Baking
{
    /// <summary>
    /// Bakes a built-in <see cref="CompositeCollider2D"/> into the package's multi-shape channel: one
    /// <see cref="PhysicsShape2D"/> per MERGED path the composite generates, with path 0 as the primary
    /// <see cref="PhysicsShape2D"/> component and the remaining paths as
    /// <see cref="PhysicsShape2DElement"/> buffer elements on the SAME body entity. A composite merges the
    /// child colliders marked composited (<c>compositeOperation != None</c>) into one combined collision
    /// surface; those children are excluded from standalone baking by
    /// <see cref="Collider2DBaking.IsUsedByComposite"/>, so the body interacts with the merged surface, not
    /// the overlapping child shapes.
    /// </summary>
    /// <remarks>
    /// <para><b>Geometry by composite type.</b> The composite exposes its merged geometry as a set of paths
    /// (<c>pathCount</c> / <c>GetPath</c>), generated by the engine; the baker reads them, it does not
    /// recompute the merge. <c>GenerateGeometry</c> is called once first so the paths are current even for a
    /// Manual-generation composite (a cheap no-op for the default Synchronous composite). Two cases:
    /// <list type="bullet">
    /// <item><b>Polygons</b> (<c>GeometryType.Polygons</c>) — each path is a closed convex region. A merged
    /// path can exceed the single-hull vertex cap, so it bakes a Polygon shape with
    /// <see cref="PhysicsShape2D.polygonDecompose"/> set: the creation system decomposes it into convex
    /// fragments via <c>PolygonGeometry.CreatePolygons</c> + <c>CreateShapeBatch</c>.</item>
    /// <item><b>Outlines</b> (<c>GeometryType.Outlines</c>) — each path is a CLOSED edge loop, so it bakes an
    /// Edge shape with <see cref="PhysicsShape2D.edgeIsLoop"/> true (a closed one-sided chain — the standard
    /// merged-level-geometry / tilemap collision surface), unlike the open <c>EdgeCollider2D</c>.</item>
    /// </list></para>
    ///
    /// <para>Surface friction/bounciness/density and the contact filter are read from the COMPOSITE's own
    /// material/layer (after the merge the body interacts with the composite, which carries the merged surface
    /// material — matching GameObject). The static-body fallback applies: a composite with no
    /// <c>Rigidbody2D</c> is static level geometry. Editor-only assembly, never in a player build.</para>
    /// </remarks>
    public sealed class CompositeCollider2DBaker : Baker<CompositeCollider2D>
    {
        public override void Bake(CompositeCollider2D authoring)
        {
            // Ensure the merged paths are current. Synchronous composites regenerate automatically; this is the
            // robustness step for a Manual composite or a not-yet-generated one, and a cheap no-op otherwise.
            authoring.GenerateGeometry();

            var pathCount = authoring.pathCount;
            if (pathCount <= 0)
                return; // an empty composite (no merged children) bakes no shape

            var entity = GetEntity(TransformUsageFlags.Dynamic);
            // Register the shared material as a bake dependency so editing it re-bakes (symmetric with the
            // custom shape baker's DependsOn(MaterialTemplate)).
            Collider2DBaking.DependsOnSharedMaterial(this, authoring);
            Collider2DBaking.ReadSurface(
                authoring,
                out var friction,
                out var bounciness,
                out var density,
                out var frictionMixing,
                out var bouncinessMixing
            );
            Collider2DBaking.ReadFilter(authoring, out var categoryBits, out var contactBits);

            // The merged paths are in the composite GameObject's local space, so the transform scale is baked
            // into each path's points (signed, winding-reversed on a mirror), the corner radius isotropically,
            // and the offset signed — the same rules the primitive bakers apply.
            var scale = Collider2DBaking.ReadScale(authoring.transform);
            var isPolygons = authoring.geometryType == CompositeCollider2D.GeometryType.Polygons;
            var edgeRadius = Collider2DBaking.ScaleRoundingRadius(authoring.edgeRadius, scale);
            var offset = Collider2DBaking.ScaleOffset((float2)authoring.offset, scale);

            var shapeIndex = 0;
            for (var p = 0; p < pathCount; p++)
            {
                var n = authoring.GetPathPointCount(p);
                if (n < (isPolygons ? 3 : 2))
                    continue; // a degenerate path (a polygon needs >=3, a chain >=2 points)

                var points = new Vector2[n];
                authoring.GetPath(p, points);

                var shape = new PhysicsShape2D
                {
                    offset = offset,
                    friction = friction,
                    bounciness = bounciness,
                    density = density,
                    frictionMixing = frictionMixing,
                    bouncinessMixing = bouncinessMixing,
                    categoryBits = categoryBits,
                    contactBits = contactBits,
                    isTrigger = false, // a composite is a solid merged surface; the composite has no isTrigger
                    vertices = BuildVertexBlob(points, scale),
                };
                if (isPolygons)
                {
                    shape.kind = PhysicsShape2DKind.Polygon;
                    shape.radius = edgeRadius;
                    // A merged Polygons path can be concave / over MaxPolygonVertices — decompose at creation.
                    shape.polygonDecompose = true;
                }
                else
                {
                    shape.kind = PhysicsShape2DKind.Edge;
                    shape.radius = edgeRadius;
                    // A composite Outlines path is a CLOSED outline — a loop chain.
                    shape.edgeIsLoop = true;
                }

                if (shapeIndex == 0)
                {
                    AddComponent(entity, shape);
                }
                else
                {
                    // Extra paths ride the DynamicBuffer<PhysicsShape2DElement> alongside the primary
                    // PhysicsShape2D. AppendToBuffer on the primary entity requires this baker to have ADDED the
                    // buffer first (it throws "component hasn't been added by the baker yet" otherwise), so add
                    // an empty buffer the first time an extra path is emitted, then append into it.
                    if (shapeIndex == 1)
                        AddBuffer<PhysicsShape2DElement>(entity);
                    AppendToBuffer(entity, new PhysicsShape2DElement { shape = shape });
                }
                shapeIndex++;
            }

            if (shapeIndex == 0)
                return; // every path was degenerate — nothing to bake, and no body for an empty composite

            Collider2DBaking.AddStaticBodyIfNoRigidbody(this);
        }

        /// <summary>
        /// Bake a path's vertices into a <see cref="PhysicsShape2DVertices"/> blob, the same form the built-in
        /// polygon/edge bakers and the custom-shape baker produce so the creation system reads it identically.
        /// The transform scale is baked into each point (signed); a winding-flipping (mirror) scale reverses
        /// the point order so a Polygons hull stays CCW and an Outlines loop's solid side is preserved.
        /// </summary>
        BlobAssetReference<PhysicsShape2DVertices> BuildVertexBlob(Vector2[] points, float2 scale)
        {
            var flip = Collider2DBaking.FlipsWinding(scale);
            var builder = new BlobBuilder(Allocator.Temp);
            ref var root = ref builder.ConstructRoot<PhysicsShape2DVertices>();
            var array = builder.Allocate(ref root.points, points.Length);
            for (var i = 0; i < points.Length; i++)
            {
                var src = flip ? points.Length - 1 - i : i;
                array[i] = (float2)points[src] * scale;
            }
            var blob = builder.CreateBlobAssetReference<PhysicsShape2DVertices>(Allocator.Persistent);
            builder.Dispose();
            AddBlobAsset(ref blob, out _);
            return blob;
        }
    }
}
